name: chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11.12
  - Flask=2.3.2
  - Flask-Cors=3.0.10 
  - pip
  - tqdm
  - requests
  - rich
  - typer
  - ujson
  - pydantic
  - smart-open
  - spacy

